# M3 T01

## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np
from scipy import stats

def funcio(arr):
    if len(arr.shape) != 1:
        print("Error: L'array no es unidimensional.")
        return
    else:
        print("Mitjana:", arr.mean())
        print("Mediana:", np.median(arr))
        print("Moda:", stats.mode(arr)[0][0])
        print("Desviació típica:", arr.std())
        print("Mínim:", arr.min())
        print("Màxim:", arr.max())


array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_2D = np.array([[10,9,8,7,6],[5,4,3,2,1]])
funcio(array)
funcio(array_2D)

Mitjana: 5.5
Mediana: 5.5
Moda: 1
Desviació típica: 2.8722813232690143
Mínim: 1
Màxim: 10
Error: L'array no es unidimensional.


/var/folders/6l/dm5_1l7j37s1g84qm0gnrpth0000gn/T/ipykernel_24392/3586723268.py:11: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Moda:", stats.mode(arr)[0][0])


## Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.



In [2]:
def quadrat_aleatori(n):
    return np.random.randint(0, 101, size=(n, n))

quadrat = quadrat_aleatori(7) #fiquem el 7 per resoldre l'exercici, pero es tracta d'un número totalment aleatori. Qualsevol número ens serviria.
print(quadrat)



[[ 13  32  49  68  61  22  52]
 [ 43  64  97  77  47  36  56]
 [ 31  30  70  92  31  41  22]
 [  0  10   5  78  83  35  21]
 [ 39  82  82  28 100  12  14]
 [ 75  95  62  15  50  82  90]
 [ 84  89  33   8   7   0  83]]


## Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [3]:
def fila_columnes_total(arr):
    fila_totals = np.sum(arr, axis=1)
    col_totals = np.sum(arr, axis=0)
    print("Files total:", fila_totals)
    print("Columnes totals:", col_totals)

nums = np.random.randint(1, 10, size=(3, 4))
print("Array: original: \n", nums)
fila_columnes_total(nums)


Array: original: 
 [[3 6 1 7]
 [3 9 8 6]
 [2 9 4 6]]
Files total: [17 26 21]
Columnes totals: [ 8 24 13 19]


## Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.



El coeficient de correlació de Pearson mesura la relació lineal entre dos variables. El valor del coeficient està entre -1 i 1. Un valor de 1 indica una relació perfectament positiva, un valor de -1 indica una relació perfectament negativa, i un valor de 0 indica cap relació. El coeficient de correlació es pot utilitzar per predir una variable a partir d'una altra o per determinar si hi ha una relació entre les variables.

In [4]:
def coeficient_correlacio(x, y):
    x_mitjana = sum(x) / len(x)
    y_mitjana = sum(y) / len(y)
    x_dif = [i - x_mitjana for i in x]
    y_dif = [i - y_mitjana for i in y]
    x_y_dif_mult = [x_dif[i] * y_dif[i] for i in range(len(x_dif))]
    x_dif_quadrat = [i ** 2 for i in x_dif]
    y_dif_quadrat = [i ** 2 for i in y_dif]
    numerador = sum(x_y_dif_mult)
    denominador = (sum(x_dif_quadrat) * sum(y_dif_quadrat)) ** 0.5
    return numerador / denominador

temperatura = [21, 22, 23, 22, 25, 20, 18]
humitat = [77, 70, 72, 68, 80, 65, 44]

print(coeficient_correlacio(temperatura, humitat))

0.8468957380356056


In [5]:
from scipy.stats import pearsonr

temperatura = [21, 22, 23, 22, 25, 20, 18]
humitat = [77, 70, 72, 68, 80, 65, 44]

correlació, p_valor = pearsonr(temperatura, humitat)
print("Comprovació coeficient correlació de Pearson amb funció de Scipy: ", correlació)


Comprovació coeficient correlació de Pearson amb funció de Scipy:  0.8468957380356056


In [6]:
correlacio = np.corrcoef(temperatura, humitat)
correlacio

array([[1.        , 0.84689574],
       [0.84689574, 1.        ]])



Un ús interessant podria ser el que plantejo al següent exemple, entre unes hipotètiques temperatures en graus Celsius i el percentatge d'humitat a l'ambient. Es pot apreciar una relació pròxima a la perfecció positiva, deixant com a dada significativa llavors, que sí existeix una correlació positiva entre temperatura i humitat.

Ho comprovo amb dues funcions diferents, amb Scipy i Numpy.